export const activityLabels: Record<string, string> = {
  project_created: "Projeto criado", project_updated: "Projeto atualizado", project_deleted: "Projeto excluído",
  project_joined: "Participação em projeto", project_member_removed: "Saída da equipe", tavern_moderated: "Mensagem removida pela moderação",
  quest_started: "Quest iniciada",
  quest_submitted: "Submissão enviada",
  quest_resubmitted: "Submissão reenviada",
  quest_completed: "Quest concluída",
  quest_rejected: "Quest rejeitada",
  quest_canceled: "Quest cancelada",
  profile_completed: "Perfil completo",
  profile_updated: "Perfil atualizado",
  achievement_unlocked: "Conquista desbloqueada",
  review_performed: "Revisão realizada",
  questTemplate_create: "Template criado",
  questTemplate_update: "Template atualizado",
  questTemplate_delete: "Template excluído",
  class_create: "Classe criada",
  class_update: "Classe atualizada",
  class_delete: "Classe excluída",
};
